name: Docker Publish

on:
  push:
    branches:
      - "master"
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/docker.yml"
      - ".vscode/**"
      - ".gitignore"
      - "LICENSE"
      - "README"

jobs:
  publish:
    needs: [base]
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    name: Build image
    steps:
      # Configure build environment
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Authenticate with GHCR
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Configure metadata
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/insertish/PortfolioStrapi

      # Build crate image
      - name: Publish
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
